meta_product_name: "Just Fish - Poissonnerie"
meta_title: "Just Fish - La mer près de chez vous"
meta_description: "Just Fish est une poissonnerie située à Wargnies le Grand, dans le Nord. Nous vous servons des produits frais, et de qualité."
meta_image: "og-image.png" # should exist in `app/assets/images/`
